Optimize gradle
Kr328/ClashForAndroid pull request #1034
Opened 2021-05-26 02:31 UTC by Goooler

- 根目录下 `build.gradle` 优化，Wrapper 使用 `configureEach` 配置
- buildSrc 下的 `build.gradle` 优化，使用 `implementation` 引入依赖

2021-05-26 03:47 UTC, Kr328 requested changes

2021-05-26 03:47 UTC, Kr328 commented on build.gradle.kts
> +tasks {
为什么要这样改 有什么改进呢

2021-05-26 03:47 UTC, Kr328 commented on buildSrc/build.gradle.kts
> +    implementation("com.google.devtools.ksp:symbol-processing-gradle-plugin:1.5.0-1.0.0-alpha10")
ksp 的依赖务必要排除 android gradle plugin
否则 ksp 引用的 agp 与应用使用的 agp 较大的时候
甚至 Sync 都过不了

2021-05-26 03:47 UTC, Kr328 commented on build.gradle.kts
> +    withType<Wrapper>().configureEach {
按照官方文档里的说明 就只应该配置 名为 "wrapper" 的 task

2021-05-26 03:53 UTC, Goooler commented on build.gradle.kts
> +    withType<Wrapper>().configureEach {
clean 是你原来就有的，只是写到闭包里面了
configureEach 比直接写 named 性能好一点

2021-05-26 03:54 UTC, Goooler commented on build.gradle.kts
> +tasks {
tasks 在同一个闭包里获取

2021-05-26 03:56 UTC, Goooler commented on buildSrc/build.gradle.kts
> +    implementation("com.google.devtools.ksp:symbol-processing-gradle-plugin:1.5.0-1.0.0-alpha10")
这就是没上 agp 7.0 的原因？

2021-05-26 04:04 UTC, Goooler commented on buildSrc/build.gradle.kts
> +    implementation("com.google.devtools.ksp:symbol-processing-gradle-plugin:1.5.0-1.0.0-alpha10")
我刚刚试了 AGP 7.0.0-beta02，ksp 排除掉 agp 之后都有问题

![image](https://user-images.githubusercontent.com/10363352/119600869-8a152200-be1a-11eb-99a9-d6208c0f26bf.png)

2021-05-26 10:47 UTC, Kr328 commented on build.gradle.kts
> +tasks {
在一个闭包里获取会有什么优势吗 会有一个额外的作用域吗

我个人不是很习惯这样写

2021-05-26 10:47 UTC, Kr328 commented on buildSrc/build.gradle.kts
> +    implementation("com.google.devtools.ksp:symbol-processing-gradle-plugin:1.5.0-1.0.0-alpha10")
4.1.X 会出现问题 高版本没有尝试

2021-05-26 10:49 UTC, Kr328 commented on build.gradle.kts
> +    withType<Wrapper>().configureEach {
clean 没有问题

只是 configureEach 的语义看起来是在对全部的 Wrapper 类型进行修改 而我只是想要修改 wrapper 这一个 task 而已

关于性能 这个脚本执行次数并不多吧 这个场景下这一点点性能是不是应该忽略

2021-05-26 10:50 UTC, Kr328 commented on buildSrc/build.gradle.kts
> +    implementation("com.google.devtools.ksp:symbol-processing-gradle-plugin:1.5.0-1.0.0-alpha10")
至于为什么不用 7.0

因为我还在用 Stable Channel 的 Android Studio

2021-05-26 11:26 UTC, Goooler commented on build.gradle.kts
> +    withType<Wrapper>().configureEach {
默认不写才是对全部执行，configureEach 是懒加载吧好像，之前有人提过

2021-05-26 11:27 UTC, Goooler commented on build.gradle.kts
> +tasks {
那可以改回去

2021-05-26 11:32 UTC, Kr328 commented on build.gradle.kts
> +    withType<Wrapper>().configureEach {
named 的话 会找 对应的类型和对应的名称 会确定就是 wrapper 这个 task

2021-05-27 02:31 UTC, Goooler commented on build.gradle.kts
> +    withType<Wrapper>().configureEach {
configureEach 会去找到这个任务的集合，应该没问题的

![image](https://user-images.githubusercontent.com/10363352/119756719-78915000-bed6-11eb-9838-f7aab05f2fb1.png)

2021-05-27 02:32 UTC, Goooler commented on buildSrc/build.gradle.kts
> +    implementation("com.google.devtools.ksp:symbol-processing-gradle-plugin:1.5.0-1.0.0-alpha10")
这个地方不排除依赖的做法我觉得可以先留着

2021-05-27 02:34 UTC, Goooler commented on build.gradle.kts
> +    withType<Wrapper>().configureEach {
为了避免争议，我还是先还原了

2021-05-27 02:38 UTC, Goooler commented on buildSrc/build.gradle.kts
> +    implementation("com.google.devtools.ksp:symbol-processing-gradle-plugin:1.5.0-1.0.0-alpha10")
我是想着先留着，buildSrc 里面改造下，用 `kotlin-dsl` 这个插件代替 `java-gradle-plugin`，把 agp 那些插件的引用放到外面的 `buildscript` 里面去

2021-05-28 02:34 UTC, Kr328 commented on buildSrc/build.gradle.kts
> +    implementation("com.google.devtools.ksp:symbol-processing-gradle-plugin:1.5.0-1.0.0-alpha10")
放在外面的 buildscript 的话就失去现在这样改的意义了

为了防止每次更新依赖都得改两遍 才改成这样的 上古版本 gradle.properties 和 buildscript 都用过

2021-05-28 02:35 UTC, Kr328 commented
那就先这样合并了 接下来还有修改再开 PR 吧

2021-05-28 02:37 UTC, merged

2021-06-10 11:58 UTC, 888520ll19811209ll approved these changes