Optimize gradle & remove unused proguard files
Kr328/ClashForAndroid pull request #1040
Opened 2021-05-29 07:58 UTC by Goooler

- 删除 `kotlinOptions` 和 `compileOptions`，因为 AGP 4.2 和 kotlin 默认的 java 版本就是 1.8
- 子模块中不需要依赖 `kotlin-stdlib-jdk7`
- 删除多余的仓库声明
- 删除无用的混淆规则文件
- `coroutines-core` 替换成 `coroutines-android` 依赖，更便于 Android 开发
- 将所有的依赖声明放在 `Libs` 里面，外部引用之

2021-05-29 10:33 UTC, Kr328 requested changes

2021-05-29 10:33 UTC, Kr328 commented on gradle/extra.gradle.kts
> +rootProject.extra.run {
我花了很长时间才脱离 extra 现在你又改回来

使用 extra 既没有补全 也没有错误提示 在什么地方引用到 IDE 也没办法找出来

所以我从很久以前就开始逃离 extra 现在请不要再改回来

2021-05-29 10:33 UTC, Kr328 commented on common/build.gradle.kts
> -            proguardFiles(
没必要删掉这个 删掉对现在的产出又没有任何提升 如果未来有需要再添加规则 还得再重写一遍 不麻烦吗

2021-05-29 10:33 UTC, Kr328 commented on app/build.gradle.kts
> -    compileOptions {
这个是为什么 低版本测试过 Java lambda 了吗

2021-05-29 10:36 UTC, Kr328 requested changes

2021-05-29 10:36 UTC, Kr328 commented on service/build.gradle.kts
> +    ksp(Libs.roomCompiler)
https://github.com/google/ksp#supported-libraries

room 的支持是 实验性的 请使用稳定实现

kaidl 用 ksp 即使出现问题我自己也能修改 而 room 不能

2021-05-29 10:39 UTC, Goooler commented on app/build.gradle.kts
> -    compileOptions {
AGP 4.2 和 kotlin 1.5 默认的 java 版本就是 1.8

2021-05-29 10:40 UTC, Goooler commented on service/build.gradle.kts
> +    ksp(Libs.roomCompiler)
好吧

2021-05-29 10:41 UTC, Goooler commented on common/build.gradle.kts
> -            proguardFiles(
这里我准备封装个方法，统一处理，类似于这样


![image](https://user-images.githubusercontent.com/10363352/120067333-88af5800-c0ad-11eb-9496-2ab8b7770845.png)

2021-05-29 10:45 UTC, Goooler commented on gradle/extra.gradle.kts
> +rootProject.extra.run {
agp 和 kotlin 这两个插件在 `buildSrc` 和根目录下的 build.gradle.kts 里都要用到，所以放在 ext 里面引用，这个文件就放一下仓库和几个插件，不需要多的改动啊。你把依赖放在 `buildSrc` 里面就不好维护啊。再说了检测什么地方引用直接全局搜那个字符串就好了，很方便啊，像这样

![image](https://user-images.githubusercontent.com/10363352/120067406-05dacd00-c0ae-11eb-96a6-7bae3cbd22ed.png)

2021-05-29 11:27 UTC, Kr328 commented on gradle/extra.gradle.kts
> +rootProject.extra.run {
所以说不需要拿到根目录的 build.gradle.kts 全部依赖全都在 buildSrc 里不好吗 只有两个文件需要管理

IDE 的 查找引用比搜索可靠多了吧 extra 编译器能查错吗

2021-05-29 11:28 UTC, Kr328 commented on common/build.gradle.kts
> -            proguardFiles(
这个没什么必要吧

会给不熟悉项目结构的人带来理解障碍

2021-05-29 11:30 UTC, Kr328 commented on common/build.gradle.kts
> -            proguardFiles(
而且 说的是混淆规则 这个不能所有模块共享的

2021-05-29 14:21 UTC, Goooler commented on common/build.gradle.kts
> -            proguardFiles(
可以共享，我现在的工程就这么做，很方便


![image](https://user-images.githubusercontent.com/10363352/120073726-30d41980-c0cc-11eb-9667-1f2322e0ad16.png)

2021-05-29 14:22 UTC, Goooler commented on gradle/extra.gradle.kts
> +rootProject.extra.run {
主要是 ksp 和 serialization 这两个插件对 buildSrc 没什么用，依赖在里面不好，所以才想着挪出来

2021-06-10 12:01 UTC, 888520ll19811209ll approved these changes

2021-06-10 12:01 UTC, 888520ll19811209ll approved these changes

2021-06-22 07:24 UTC, Goooler commented
@Kr328 有空处理一下喽

2021-09-04 08:41 UTC, fanck0605 commented on design/build.gradle.kts
> -    }
这个为啥要移除。下次人家默认值变了，target 就不对了。

2021-09-04 08:57 UTC, Goooler commented on design/build.gradle.kts
> -    }
下次变了再说，或者统一升级为 java 11

2021-09-10 10:19 UTC, closed without merging