Optimize CI a bit
Kr328/ClashForAndroid pull request #1414
Opened 2022-03-02 05:42 UTC by Goooler

2022-03-02 05:43 UTC, Goooler commented on .github/workflows/build-unsigned.yaml
> +          arguments: --no-daemon app:assembleFossRelease
https://github.com/gradle/gradle-build-action

Ref https://github.com/detekt/detekt/pull/3723, it's really so fast to run jobs, and many other advantages.

2022-03-02 05:44 UTC, Goooler commented on .github/workflows/build-unsigned.yaml
> +          java-version: 17
Java 17, faster.

2022-03-22 06:00 UTC, Kr328 requested changes

2022-03-22 06:00 UTC, Kr328 commented on .github/workflows/build-unsigned.yaml
>            go-version: 1.17
Bump to go 1.18 please

2022-03-22 06:07 UTC, Goooler commented on .github/workflows/build-unsigned.yaml
>            go-version: 1.17
```suggestion
          go-version: 1.18
```

2022-03-22 06:09 UTC, Goooler commented on .github/workflows/build-unsigned.yaml
>            go-version: 1.17
32610a4f490eba070cc2a0738eb1dfe05c0c70ee

2022-03-22 10:41 UTC, merged